apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mongodb
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 10.31.1
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: secrets
              key: user
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: password
  interval: 1m0s
  releaseName: mongodb-10.31.1
